export FZF_DEFAULT_COMMAND="rg --files --hidden"
export EDITOR=nvim
export VISUAL=nvim
export TERMINAL=alacritty
export TERM=alacritty
export BROWSER=com.github.Eloston.UngoogledChromium
export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$HOME/.config/zsh/custom
export PATH=$HOME/.yarn/bin:$HOME/.local/bin:$HOME/.cargo/bin:$PATH
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export ANDROID_IP=192.168.2.160:5555
